name: Test (macOS ARM64 only)

on:
  workflow_dispatch:  # Run manually from Actions tab
  push:
    branches: [ pip_install ]
  pull_request:
    branches: [ pip_install ]

jobs:
  test-mac-arm64:
    runs-on: macos-14-arm64
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build/test dependencies
        run: |
          python -m pip install --upgrade pip build wheel pybind11 setuptools pytest

      - name: Build the wheel
        run: |
          python -m build

      - name: Install package
        run: |
          pip install dist/*.whl

      - name: Run tests
        run: |
          pytest tests/
