name: Build and Test

on:
  push:
    branches: [ pip_install ]
  pull_request:
    branches: [ pip_install ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build tool
        run: python -m pip install build
      - name: Build package (PEP 517)
        run: python -m build
      - name: Install wheel
        run: python -m pip install dist/*.whl
      - name: Run a quick import test
        run: |
          python -c "from py_gpmf_parser.gopro_telemetry_extractor import GoProTelemetryExtractor"

